name: hetmech-backend
channels:
  - conda-forge
dependencies:
  - django-cors-headers=3.2.1
  - django-extensions=2.2.9
  - django-filter=2.3.0
  - django=3.0.7
  - djangorestframework=3.11.0
  - graphviz=2.42.3
  - gunicorn=20.0.4
  - ipykernel=5.3.0
  - markdown=3.2.2
  - neo4j-python-driver=4.2.1
  - numpy=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - psycopg2=2.8.5
  - pydot=1.4.1
  - python=3.8.3
  - pyyaml=5.3.1
  - requests=2.24.0
  - scipy=1.4.1
  - sqlparse=0.3.1
  - pip:
    - git+https://github.com/hetio/hetnetpy@aa16e6a7092c039a6b175a73a35c006e53acee20
    - git+https://github.com/hetio/hetmatpy@bc36aa9859c43a1a5fb22808cd6eb952ef9d497c
