name: hetmech-backend
channels:
  - conda-forge
dependencies:
  - django=2.2
  - django-cors-headers=2.5.0
  - django-extensions=2.1.6
  - django-filter=2.1.0
  - djangorestframework=3.9.2
  - graphviz=2.40.1
  - gunicorn=19.9.0
  - ipykernel=5.1.0
  - neo4j-python-driver=1.7.2
  - pandas=0.24.2
  - pip=19.0.3
  - psycopg2=2.8.2
  - pydot=1.4.1
  - python=3.7.3
  - pyyaml=5.1
  - requests=2.21.0
  - scipy=1.2.1
  - sqlparse=0.3.0
  - pip:
    - git+https://github.com/hetio/hetio@0568e3f3783983e77517158f63661eddc9765f73
    - git+https://github.com/hetio/hetmatpy@4de8877c93fdaea29de4ea72c4e61499dd4c02e1
